### ISSUE TITLE
The text-overflow mixin is named like a css key…

### ISSUE THREAD

**Issue by flying-sheep** [maxmx/bootstrap-stylus#37]
…which makes is being treated as transparent mixin in code:

``` css
h2
    text-overflow '–'
```

surprisingly compiles to

``` css
h3 {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

this can only be circumvented using `@css { text-overflow: '–'; }` instead which is ugly.

---

a fix that doesn’t break backwards-compatibility:

``` css
text-overflow()
    if arguments
        text-overflow arguments
    else
        overflow hidden
        white-space nowrap
        text-overflow ellipsis
```

with the test case

``` css
h1
    text-overflow()

h2
    text-overflow '–'
```

compiling to

``` css
h1 {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
h2 {
  text-overflow: '–';
}
```
