### ISSUE TITLE
Tabs have line at bottom when justified

### ISSUE THREAD

**Issue by neverfox** [maxmx/bootstrap-stylus#40]
The following code is doesn't appear to actually bring in the `nav-tabs-justified` mixin:

```
&.nav-justified {
  nav-justified();
  nav-tabs-justified();
}
```

If I just use just use `nav nav-tabs nav-justified` as shown in the docs, I get a border under the active tab. I have to explicitly add the `nav-tabs-justified` class to get the correct behavior, but that shouldn't be necessary (and isn't in standard Bootstrap).

Looking at the official Bootrstrap CSS, none of the following end up in the compiled css from Stylus:

``` css
.nav-tabs.nav-justified {
  width: 100%;
  border-bottom: 0;
}
.nav-tabs.nav-justified > li {
  float: none;
}
.nav-tabs.nav-justified > li > a {
  margin-bottom: 5px;
  text-align: center;
}
.nav-tabs.nav-justified > .dropdown .dropdown-menu {
  top: auto;
  left: auto;
}
@media (min-width: 768px) {
  .nav-tabs.nav-justified > li {
    display: table-cell;
    width: 1%;
  }
  .nav-tabs.nav-justified > li > a {
    margin-bottom: 0;
  }
}
.nav-tabs.nav-justified > li > a {
  margin-right: 0;
  border-radius: 4px;
}
.nav-tabs.nav-justified > .active > a,
.nav-tabs.nav-justified > .active > a:hover,
.nav-tabs.nav-justified > .active > a:focus {
  border: 1px solid #ddd;
}
@media (min-width: 768px) {
  .nav-tabs.nav-justified > li > a {
    border-bottom: 1px solid #ddd;
    border-radius: 4px 4px 0 0;
  }
  .nav-tabs.nav-justified > .active > a,
  .nav-tabs.nav-justified > .active > a:hover,
  .nav-tabs.nav-justified > .active > a:focus {
    border-bottom-color: #fff;
  }
}
```
